Repository tsunamods-codes/7th-Heaven, pull requests merged in 2023-01, with the labels that each got.

#124 RegistryHelper: Fix double backslash path
  7thHeaven.Code/RegistryHelper.cs
Labels: bug

#127 7thWrapperLoader: Tweak the .NET error message
  7thWrapperLoader/dllmain.cpp
Labels: enhancement

#128 RegistryHelper: Fix equality registry value for Guid
  7thHeaven.Code/RegistryHelper.cs
Labels: bug

#132 Update 7H_GameDriver_UI.xml
  SeventhHeavenUI/Resources/7H_GameDriver_UI.xml
Labels: documentation, enhancement

#133 UI: Make upgrade/downgrade messages more human-readable
  7thHeaven.Code/RegistryHelper.cs
  7thWorkshop/Program.cs
  README.md
  SeventhHeavenUI/Classes/FFNxDriverUpdater.cs
  SeventhHeavenUI/Classes/UpdateChecker.cs
Labels: enhancement
